version: '3.7'
services:
   books-ui:
      container_name: books-ui
      build:
         context: ./books-ui
         dockerfile: Dockerfile
      environment:
         BACKEND_API: ${BACKEND_API:-http://localhost:8002}
         CONTENT_API: ${CONTENT_API:-http://localhost:8001}
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./books-ui:/app
         - /app/node_modules
      networks:
         - books-network
      depends_on:
         -  backend-api
   database-api:
      build:
         context: books_database_api
         dockerfile: Dockerfile
      container_name: database-api
      environment:
         g: ${ELASTIC_SEARCH_URL:-books-elastics-db}
         ELASTIC_SEARCH_PORT: ${ELASTIC_SEARCH_PORT:-9200}
         REDIS_ENDPOINT: ${REDIS_ENDPOINT:-redis-image}
      depends_on:
         -  books-elastics-db
      ports:
         - "8001:80"
      networks:
         - books-network
      volumes:
         - ./books_database_api:/app
   books-elastics-db:
      environment:
         - discovery.type=single-node
      container_name: books-elastics-db
      image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
      ports:
         - "9201:9200"
         - "9301:9300"
      volumes:
         -  books_elastic_db:/usr/share/elasticsearch/data
      networks:
         - books-network
   redis-image:
      image: redis:6.2
      container_name: redis-image
      networks:
         - books-network
   books-postgres-db:
      container_name: books-postgres-db
      build:
         context: books_backend
         dockerfile: Dockerfile.db
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
         POSTGRES_USER:  ${POSTGRES_USER:-test}
      ports:
         -  "5432:5432"
      networks:
         - books-network
      volumes:
         -  books_postgres_db:/var/lib/postgresql/data
   backend-api:
      build:
         context: books_backend
         dockerfile: Dockerfile
      container_name: backend-api
      environment:
         ELASTIC_SEARCH_URL: ${ELASTIC_SEARCH_URL:-books-elastics-db}
         ELASTIC_SEARCH_PORT: ${ELASTIC_SEARCH_PORT:-9200}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
         POSTGRES_USER: ${POSTGRES_USER:-test}
         POSTGRES_PORT: ${POSTGRES_PORT:-5432}
         POSTGRES_URL: ${POSTGRES_URL:-books-postgres-db}
         POSTGRES_DATABASE: ${POSTGRES_DATABASE:-books}
      depends_on:
         - database-api
         - books-postgres-db
      ports:
         - "8002:80"
      networks:
         - books-network
      volumes:
         -  ./books_backend:/app
networks:
   books-network:
      driver: bridge

volumes:
   books_elastic_db:
      driver: local
   books_postgres_db: {}