"""rating score

Revision ID: 3ed9794ef631
Revises: 708e4e906087
Create Date: 2021-10-27 00:01:32.580980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed9794ef631'
down_revision = '708e4e906087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'score')
    # ### end Alembic commands ###
