"""more book metadata

Revision ID: 455d0a894f09
Revises: c95263499e3e
Create Date: 2021-10-21 02:26:18.328051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455d0a894f09'
down_revision = 'c95263499e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'language')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
