"""rating review

Revision ID: 708e4e906087
Revises: 6cc88673c29b
Create Date: 2021-10-26 01:00:22.561544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708e4e906087'
down_revision = '6cc88673c29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('review', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'review')
    # ### end Alembic commands ###
