"""fiction separately

Revision ID: b46424d9fcfc
Revises: db8bb4d478b2
Create Date: 2021-11-11 21:05:00.755930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46424d9fcfc'
down_revision = 'db8bb4d478b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_fiction', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_fiction')
    # ### end Alembic commands ###
