"""add content length for books

Revision ID: db8bb4d478b2
Revises: eaa2c3c78b6d
Create Date: 2021-11-04 13:52:41.377798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8bb4d478b2'
down_revision = 'eaa2c3c78b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('content_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'content_length')
    # ### end Alembic commands ###
